name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: yarn

    # Fix `yarn install --frozen-lockfile` not working in monorepo.
    # https://github.com/yarnpkg/yarn/issues/5840#issuecomment-468782288
    - name: Get checksum before yarn install
      id: yarn-lock-check-before
      run: echo "::set-output name=sum::$(cksum yarn.lock)"

    - run: yarn install --frozen-lockfile

    - name: Get checksum after yarn install
      id: yarn-lock-check-after
      run: echo "::set-output name=sum::$(cksum yarn.lock)"

    - name: Exit if yarn.lock updated
      run: exit 1
      if: steps.yarn-lock-check-before.outputs.sum != steps.yarn-lock-check-after.outputs.sum

    - run: yarn build

    - name: Deploy to Netlify (pull request)
      id: netlify-deploy
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: ./build
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "${{ github.event.pull_request.title }}"
        alias: docs-preview-${{ github.event.number }}
        netlify-config-path: ./netlify.toml
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 2
      if: github.event_name == 'pull_request'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GH_TOKEN_EVE }}
        external_repository: easyops-cn/brick-next
        cname: brick-next.js.org
        publish_dir: ./build
        publish_branch: gh-pages
        force_orphan: true
      if: github.event_name == 'push'